version: "3.3"
services:
  mbed_os_dev:
    command: ['/root/Config/build.sh']
    env_file:
      - ../.env
    volumes:
      - "../examples/mbed-cloud-client-example/mbedos_k64f_avnet_cellular_wnc14a2a:/root/Config"
      - "../creds:/root/Creds"
      - "../share:/root/Share"
    container_name: mbedos_k64f_avnet_cellular_wnc14a2a
